name: Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 358  # 5 hours and 58 minutes timeout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          TO_EMAIL: $ {{secrets.TO_EMAIL}}
          PASSWORD: $ {{secrets.TO_EMAIL}}
          EMAIL: $ {{secrets.EMAIL}}
          SMTP_SERVER: $ {{secrets.SMTP_SERVER}}
          EXCHANGE_API_KEY: $ {{ secrets.EXCHANGE_API_KEY}}
      - name: Test with pytest
        run: |
         Main.py
